"""
Django settings for bg_store project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from util import secret_codes
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xqth3z#z-i!aj-2yq&0w&k5*x-kza+m+)n-%cj+4_=z!w0k9f@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'orders.apps.OrdersConfig',
    'payments.apps.PaymentsConfig',
    'openpyxl',
    'social_django',
    'django.contrib.sites',
    'fontawesome-free',
    'products_stock.apps.ProductsStockConfig',
    'users.apps.UsersConfig',  # since it is above auth, createsuperuser will be used from here instead of auth.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bg_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bg_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        "PORT": "3306",
        'NAME': "bg_store_database",
        "USER": "root",
        "PASSWORD": secret_codes.DB_PASSWORD

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'chraifdiab@gmail.com'
EMAIL_HOST_PASSWORD = secret_codes.email_host_pw
DEFAULT_FROM_EMAIL = "chraifdiab@gmail.com"

AUTH_USER_MODEL = 'users.AuthUser'

# GENERAL social auth
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',

]
SOCIAL_AUTH_URL_NAMESPACE = 'users:account:social'
SOCIAL_AUTH_LOGIN_URL = '/'
# Google social auth
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = secret_codes.google_oauth_key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = secret_codes.google_oauth_key_secret
# fb social auth
SOCIAL_AUTH_FACEBOOK_KEY = secret_codes.fb_auth_key
SOCIAL_AUTH_FACEBOOK_SECRET = secret_codes.fb_auth_key_secret
SOCIAL_AUTH_FACEBOOK_API_VERSION = '11.0'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'public_profile']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'email,first_name,last_name',
}

#STRIPE

STRIPE_PUBLIC_KEY = secret_codes.stripe_pub_key
STRIPE_SECRET_KEY = secret_codes.stripe_secret_key

LOGIN_URL = 'users:account:login'

# SITES

SITE_ID = 1

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'users.social_auth_pipelines.create_user',
    'users.social_auth_pipelines.get_profile_picture',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# TO DO:

# DONE:
# category name should be a choice DONE

# searching by id breaks the site atm, fix it DONE

# make publisher link take to a publisher page
# with details and all releases DONE

# make it so that arrows don't appear if there are no prev pages DONE

# Payments without 3d secure do not work, need to send property through redirect.

# Add ability to upload zip files  with images

# download financial details

# orders update order db

# can't log in through facebook?!?!? ( need to update dev facebook settings)


# NOT DONE:

# CONTACT ME send mail directly to admin https://docs.djangoproject.com/en/3.2/topics/forms/

# baseline cart requires log-in, modify it such that it works with
# or without login or at the very least defaults you to a log in page instead
# of crashing

# Pretty up the publisher page, add filters and pagination.

# make the images tab display all game images on the image page separately from
# the game cover and pretty up the product pages + add to cart button in.

# pretty up notifications. add them to profile page.
