# Generated by Django 3.1.7 on 2021-06-06 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stripecard',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
