# Generated by Django 3.1.7 on 2021-05-01 21:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(default=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='150cf0275e0e18b0d822cc9edf18983e9b210fe1d82dd86d378cbe3ea1d0ef33', max_length=64)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 53, 17, 69810, tzinfo=utc))),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
