# Generated by Django 3.1.7 on 2021-05-01 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210502_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 21, 56, 20, 742102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='3fc6ae754e7cecac29ce9535c48d2202da50dfc86075a86ecd5cbd27f3986001', max_length=64),
        ),
    ]
