# Generated by Django 3.1.7 on 2021-05-02 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210502_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 9, 49, 16, 773747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='2d79f742c730db80bb628cc178f6d35aa2c280c02eb3d1cba3866932b8a25836', max_length=64),
        ),
    ]
