# Generated by Django 3.1.7 on 2021-05-02 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210502_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 9, 50, 5, 113498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='c65d189bacc893ee9faed64448f8df799648e7cab3a5a6c2e0b23e2486da6758', max_length=64),
        ),
    ]
