# Generated by Django 3.1.7 on 2021-05-02 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210502_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 10, 29, 4, 499840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='6fc05d66dcef7c4888e96e19156a6b183c6a00ba8085470d93d4f8eea01dd6d0', max_length=64),
        ),
    ]
