# Generated by Django 3.1.7 on 2021-05-04 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210502_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 18, 48, 10, 570125)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='001b20c41d6834a0aaa124900faed4f5c955a9c3609cf3ef11ad0bb2809a97b5', max_length=64),
        ),
    ]
