# Generated by Django 3.1.7 on 2021-05-08 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210504_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 14, 27, 41, 894390)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='6c099dbd32b6c2caaadee0c639e3a537a42c315c6a1b4ebbd7d9ce2850fb1d33', max_length=64),
        ),
    ]
