# Generated by Django 3.1.7 on 2021-06-05 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210508_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 16, 55, 21, 654038)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='5a2497e299b49217bc93eae5bd176371dac0c9900011cb9f125066bcf997667e', max_length=64),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
