# Generated by Django 3.1.7 on 2021-06-06 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210605_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 5, 8, 18, 897769)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='681f21c454551f4dd234b4a3143b5230607d6f72ff695b817f80d531d94727dc', max_length=64),
        ),
    ]
