# Generated by Django 3.1.7 on 2021-06-07 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210607_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 3, 47, 40, 21384)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='0b209c344618be1be169d5c768d37b3eaa5fd0931fefed24a8e0969f1590b691', max_length=64),
        ),
    ]
