# Generated by Django 3.1.7 on 2021-06-07 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210607_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 8, 5, 10, 71454)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='f49e90efde76b461f22731f39b50935f60db1f3274851c810084a2533592c516', max_length=64),
        ),
    ]
