# Generated by Django 3.1.7 on 2021-06-07 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210607_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 19, 39, 12, 604098)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='49daf8d2be3aafdb41704c2f3851e8e6169ec344814420b22964be7d1a25e072', max_length=64),
        ),
    ]
