# Generated by Django 3.1.7 on 2021-06-08 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210608_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 2, 59, 48, 41237)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='b1df24df51dc29753ebbcf0c325ee0d84e6570265a18f0494e941369bf9b7a01', max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
