# Generated by Django 3.1.7 on 2021-06-14 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210609_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 2, 8, 41, 839859)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='ff0b291d762ff57601c02a3593cca431e638456c14bb652602074bf3240c5d5f', max_length=64),
        ),
    ]
