# Generated by Django 3.1.7 on 2021-06-14 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210614_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 3, 47, 47, 368503)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='aa94c97a27781c69541d074b2b9e88ddf2b3a884c144c121da59406cf721e53f', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=255),
        ),
    ]
