# Generated by Django 3.1.7 on 2021-06-14 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210614_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 7, 29, 17, 782906)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='3fca726bac26f5a90d5d44107618e04d1295206fdb3fc598236bcfb5c6c961af', max_length=64),
        ),
    ]
