# Generated by Django 3.1.7 on 2021-05-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='publisher image')),
                ('details', models.CharField(max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(null=True)),
                ('image_cover', models.ImageField(upload_to='product image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('player_count', models.CharField(max_length=10)),
                ('new_stock', models.IntegerField(default=0)),
                ('used_stock', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('bgg_link', models.CharField(default='https://boardgamegeek.com/', max_length=250)),
                ('image_game', models.ImageField(upload_to='product image')),
                ('category_name', models.CharField(default='Product', max_length=40)),
                ('game_genre', models.CharField(choices=[('AC', 'Accessory'), ('FG', 'Family Game'), ('DG', 'Dexterity Game'), ('PG', 'Party Game'), ('A', 'Abstract Game'), ('TG', 'Thematic Game'), ('EG', 'Eurogame'), ('WG', 'Wargame')], default='AC', max_length=2)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_stock.publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
