# Generated by Django 3.1.7 on 2021-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='game_genre',
            field=models.CharField(choices=[('AC', 'Accessory'), ('FG', 'Family Game'), ('DG', 'Dexterity Game'), ('PG', 'Party Game'), ('A', 'Abstract Game'), ('TG', 'Thematic Game'), ('EG', 'Eurogame'), ('WG', 'Wargame'), ('AR', 'Area Control'), ('L', 'Legacy'), ('DB', 'Deckbuilder'), ('DR', 'Drafting'), ('DC', 'Dungeon Crawler'), ('WP', 'Worker Placement')], default='AC', max_length=2),
        ),
    ]
