# Generated by Django 3.1.7 on 2021-05-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0002_auto_20210502_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='game_genre',
            new_name='genre',
        ),
    ]
