# Generated by Django 3.1.7 on 2021-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_stock', '0005_auto_20210605_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
